### ISSUE TITLE
Toposes and Topoi

### ISSUE THREAD

**Issue by ghost** [thosgood/sga#4]
I want to discuss the pros and cons of the two translations. The two of them are correct plurals of topos.

"Topoi" accentuate the greek root, "toposes" their English usage. It is true that regarding the use of the community of them, "toposes" are more widely used, but regarding a translation of Grothendieck's work, I think it is better if we use his. I have never seen the word "toposes" in his works. He uses "Topoi".

**Comment by thosgood** [comment]
I agree that "topoi" is probably much more Grothendieckien, but "toposes" just sounds so much more natural to my ear that I default to it when writing/translating. It's similar to how I probably always use British spellings, and using "-sation" instead of "-zation" regardless of etymological roots. I guess it's about finding a balance between the translation being "faithful" to the original language, but also sounding good to the ear of a speaker in the new language (here, English).
